import { componentSources } from './componentSources'
import { getFontReadmeSection } from './fontExport'
import type { Theme } from '../theme/types'

function componentList(): string {
  return componentSources.map((c) => `- ${c.name}`).join('\n')
}

export function buildComponentsOnlyReadme(theme: Theme, fontId: string): string {
  return `# HueSys Components

Portable component source, styles, and theme tokens generated by HueSys, ready to drop into an existing React application.

## What's included

- \`components/\` — ${componentSources.length} production-ready React components, source only (no build step, no bundled package)
- \`styles/theme.css\` — the resolved design tokens as CSS custom properties
- \`styles/_mixins.scss\` — the small set of shared Sass mixins the components themselves use
- \`index.ts\` — a single barrel export for every component and its prop types

## Requirements

Your project needs:

- React 19+
- TypeScript
- A Sass-capable build (Vite, webpack + sass-loader, etc. all work) — components import their own \`.scss\` file directly

This is not an npm package. Copy the \`components/\`, \`styles/\`, and \`index.ts\` into your project (e.g. as \`src/huesys-components/\`) and import from there.

If you open this folder on its own — before copying it into a project — your editor may show errors like \`Cannot find module 'react/jsx-runtime'\` or \`JSX.IntrinsicElements\`. That's expected: this folder intentionally ships without its own \`package.json\` or TypeScript config, so nothing here declares a React/TypeScript environment on its own. The errors resolve once the files are inside a project with React, TypeScript, and \`@types/react\` installed.

## Using the theme

Import \`styles/theme.css\` once, near your app's entry point, before any component renders:

\`\`\`ts
import './huesys-components/styles/theme.css'
\`\`\`

It defines every CSS custom property (\`--color-primary\`, \`--font-family\`, \`--radius-md\`, etc.) the components read from. Every value is already resolved and literal — no build-time processing required.

${getFontReadmeSection(fontId, theme)}

## Using the components

\`\`\`tsx
import { Button, Card, Input } from './huesys-components'

function Example() {
  return (
    <Card>
      <Input placeholder="you@example.com" />
      <Button variant="primary">Get started</Button>
    </Card>
  )
}
\`\`\`

Every component accepts the same props as its native HTML element (e.g. \`ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement>\`) plus a small number of its own — see each component's exported \`*Props\` type.

## Components included

${componentList()}
`
}

export function buildStarterReadme(theme: Theme, fontId: string): string {
  return `# HueSys Starter Project

A complete Vite + React + TypeScript + SCSS project, generated by HueSys, containing your generated design system and a small demo page.

## Getting started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open the printed local URL — the demo page renders every generated component using your Theme.

## What's included

- \`src/components/\` — ${componentSources.length} production-ready React components
- \`src/styles/theme.css\` — the resolved design tokens as CSS custom properties
- \`src/styles/_mixins.scss\` — the shared Sass mixins the components use
- \`src/styles/global.scss\` — a minimal CSS reset and base body styling
- \`src/App.tsx\` — a small demo page using the components — replace freely, it's a starting point, not required scaffolding

${getFontReadmeSection(fontId, theme)}

## Components included

${componentList()}

## Build

\`\`\`bash
npm run build
\`\`\`

Produces a production build in \`dist/\`.
`
}
